import type { Job, EmployerProfile, JobCategory, JobApplication } from './types'

// Mock Job Categories with counts
export const mockCategories: JobCategory[] = [
  { id: 'it', name: 'Information Technology', slug: 'it', jobCount: 1250 },
  { id: 'construction', name: 'Construction & Engineering', slug: 'construction', jobCount: 890 },
  { id: 'healthcare', name: 'Healthcare & Medical', slug: 'healthcare', jobCount: 650 },
  { id: 'finance', name: 'Finance & Accounting', slug: 'finance', jobCount: 420 },
  { id: 'sales', name: 'Sales & Marketing', slug: 'sales', jobCount: 780 },
  { id: 'hospitality', name: 'Hospitality & Tourism', slug: 'hospitality', jobCount: 340 },
]

// Mock Companies
export const mockCompanies: EmployerProfile[] = [
  {
    id: '1',
    userId: 'u1',
    companyName: 'Saudi Aramco',
    companyLogoUrl: '/logos/aramco.png',
    industry: 'Oil & Gas',
    companySize: '1000+',
    website: 'https://aramco.com',
    locationCity: 'Dhahran',
    locationRegion: 'Eastern Province',
    description: 'Saudi Aramco is one of the world\'s largest integrated energy and chemicals companies.',
    isVerified: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    userId: 'u2',
    companyName: 'NEOM',
    companyLogoUrl: '/logos/neom.png',
    industry: 'Real Estate',
    companySize: '501-1000',
    website: 'https://neom.com',
    locationCity: 'NEOM',
    locationRegion: 'Tabuk',
    description: 'NEOM is a bold and audacious dream that is taking shape in northwest Saudi Arabia.',
    isVerified: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    userId: 'u3',
    companyName: 'STC',
    companyLogoUrl: '/logos/stc.png',
    industry: 'Telecommunications',
    companySize: '1000+',
    website: 'https://stc.com.sa',
    locationCity: 'Riyadh',
    locationRegion: 'Riyadh',
    description: 'Saudi Telecom Company is the largest telecommunications company in the Middle East.',
    isVerified: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    userId: 'u4',
    companyName: 'SABIC',
    companyLogoUrl: '/logos/sabic.png',
    industry: 'Manufacturing',
    companySize: '1000+',
    website: 'https://sabic.com',
    locationCity: 'Riyadh',
    locationRegion: 'Riyadh',
    description: 'SABIC is a global leader in diversified chemicals headquartered in Riyadh.',
    isVerified: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    userId: 'u5',
    companyName: 'Red Sea Global',
    companyLogoUrl: '/logos/redsea.png',
    industry: 'Hospitality & Tourism',
    companySize: '201-500',
    website: 'https://redseaglobal.com',
    locationCity: 'Riyadh',
    locationRegion: 'Riyadh',
    description: 'Red Sea Global is the developer behind the world\'s most ambitious regenerative tourism destinations.',
    isVerified: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    userId: 'u6',
    companyName: 'Alpha Ultimate Ltd.',
    companyLogoUrl: '/logos/alpha.png',
    industry: 'Construction & Engineering',
    companySize: '51-200',
    website: 'https://alphaultimate.com',
    locationCity: 'Jeddah',
    locationRegion: 'Makkah',
    description: 'Alpha Ultimate delivers comprehensive services spanning construction, cleaning, and labor supply powered by AI.',
    isVerified: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Mock Jobs
export const mockJobs: Job[] = [
  {
    id: '1',
    employerId: '1',
    employer: mockCompanies[0],
    title: 'Senior Software Engineer',
    locationCity: 'Dhahran',
    locationRegion: 'Eastern Province',
    employmentType: 'FULL_TIME',
    salaryMin: 25000,
    salaryMax: 40000,
    currency: 'SAR',
    experienceLevel: 'SENIOR',
    categoryId: 'it',
    description: 'We are looking for a Senior Software Engineer to join our digital transformation team. You will be responsible for designing, developing, and maintaining high-quality software solutions.',
    responsibilities: 'Design and implement scalable software solutions\nLead technical discussions and code reviews\nMentor junior developers\nCollaborate with cross-functional teams',
    requirements: '7+ years of software development experience\nProficiency in Python, Java, or C++\nExperience with cloud platforms (AWS, Azure, GCP)\nStrong problem-solving skills',
    benefits: 'Competitive salary\nHealth insurance\nAnnual bonus\nProfessional development',
    status: 'PUBLISHED',
    postedAt: new Date('2024-01-15'),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    applicationsCount: 45,
  },
  {
    id: '2',
    employerId: '2',
    employer: mockCompanies[1],
    title: 'Project Manager - Construction',
    locationCity: 'NEOM',
    locationRegion: 'Tabuk',
    employmentType: 'FULL_TIME',
    salaryMin: 30000,
    salaryMax: 50000,
    currency: 'SAR',
    experienceLevel: 'SENIOR',
    categoryId: 'construction',
    description: 'Join NEOM and be part of building the future. We are seeking an experienced Project Manager to oversee major construction projects.',
    responsibilities: 'Manage project timelines and budgets\nCoordinate with contractors and stakeholders\nEnsure compliance with safety standards\nReport progress to senior management',
    requirements: '10+ years in construction project management\nPMP certification preferred\nExperience with mega-projects\nExcellent leadership skills',
    benefits: 'Relocation package\nHousing allowance\nHealth coverage\nCareer growth opportunities',
    status: 'PUBLISHED',
    postedAt: new Date('2024-01-14'),
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
    applicationsCount: 28,
  },
  {
    id: '3',
    employerId: '3',
    employer: mockCompanies[2],
    title: 'Network Engineer',
    locationCity: 'Riyadh',
    locationRegion: 'Riyadh',
    employmentType: 'FULL_TIME',
    salaryMin: 18000,
    salaryMax: 28000,
    currency: 'SAR',
    experienceLevel: 'MID',
    categoryId: 'it',
    description: 'STC is looking for a skilled Network Engineer to maintain and optimize our telecommunications infrastructure.',
    responsibilities: 'Design and implement network solutions\nTroubleshoot network issues\nManage network security\nDocument network configurations',
    requirements: '5+ years network engineering experience\nCCNA/CCNP certification\nExperience with Cisco and Juniper equipment\nKnowledge of 5G technologies',
    benefits: 'Mobile phone allowance\nTransportation\nMedical insurance\nPerformance bonus',
    status: 'PUBLISHED',
    postedAt: new Date('2024-01-13'),
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
    applicationsCount: 62,
  },
  {
    id: '4',
    employerId: '4',
    employer: mockCompanies[3],
    title: 'Chemical Engineer',
    locationCity: 'Jubail',
    locationRegion: 'Eastern Province',
    employmentType: 'FULL_TIME',
    salaryMin: 20000,
    salaryMax: 35000,
    currency: 'SAR',
    experienceLevel: 'MID',
    categoryId: 'construction',
    description: 'SABIC is seeking a Chemical Engineer to join our world-class manufacturing facilities in Jubail.',
    responsibilities: 'Optimize chemical processes\nConduct safety assessments\nDevelop process improvements\nCollaborate with R&D team',
    requirements: 'BSc in Chemical Engineering\n5+ years in petrochemical industry\nProcess simulation experience\nStrong analytical skills',
    benefits: 'Competitive package\nHousing\nEducation allowance\nEnd of service benefits',
    status: 'PUBLISHED',
    postedAt: new Date('2024-01-12'),
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
    applicationsCount: 34,
  },
  {
    id: '5',
    employerId: '5',
    employer: mockCompanies[4],
    title: 'Resort Operations Manager',
    locationCity: 'Red Sea',
    locationRegion: 'Tabuk',
    employmentType: 'FULL_TIME',
    salaryMin: 22000,
    salaryMax: 38000,
    currency: 'SAR',
    experienceLevel: 'SENIOR',
    categoryId: 'hospitality',
    description: 'Lead the operations of our luxury resort destination at Red Sea Global.',
    responsibilities: 'Oversee daily resort operations\nManage guest experience\nLead hospitality team\nEnsure service excellence',
    requirements: '8+ years in luxury hospitality\nDegree in Hotel Management\nMultilingual preferred\nLeadership experience',
    benefits: 'Staff accommodation\nMeals provided\nTravel benefits\nCareer development',
    status: 'PUBLISHED',
    postedAt: new Date('2024-01-11'),
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
    applicationsCount: 19,
  },
  {
    id: '6',
    employerId: '6',
    employer: mockCompanies[5],
    title: 'Civil Site Engineer',
    locationCity: 'Jeddah',
    locationRegion: 'Makkah',
    employmentType: 'FULL_TIME',
    salaryMin: 12000,
    salaryMax: 18000,
    currency: 'SAR',
    experienceLevel: 'JUNIOR',
    categoryId: 'construction',
    description: 'Alpha Ultimate is hiring a Civil Site Engineer for construction projects in Jeddah.',
    responsibilities: 'Supervise construction activities\nEnsure quality control\nCoordinate with contractors\nPrepare progress reports',
    requirements: 'BSc in Civil Engineering\n2-4 years experience\nAutoCAD proficiency\nGood communication skills',
    benefits: 'Accommodation\nTransportation\nMedical insurance\nAnnual leave',
    status: 'PUBLISHED',
    postedAt: new Date('2024-01-10'),
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    applicationsCount: 87,
  },
  {
    id: '7',
    employerId: '1',
    employer: mockCompanies[0],
    title: 'Data Scientist',
    locationCity: 'Dhahran',
    locationRegion: 'Eastern Province',
    employmentType: 'FULL_TIME',
    salaryMin: 28000,
    salaryMax: 45000,
    currency: 'SAR',
    experienceLevel: 'SENIOR',
    categoryId: 'it',
    description: 'Join Aramco\'s Data & Analytics team to drive data-driven decision making across the organization.',
    responsibilities: 'Develop ML models\nAnalyze complex datasets\nCreate data visualizations\nCollaborate with business teams',
    requirements: 'MSc in Data Science or related field\n6+ years experience\nProficiency in Python, R, SQL\nExperience with big data tools',
    benefits: 'World-class facilities\nResearch opportunities\nGenerous benefits\nGlobal exposure',
    status: 'PUBLISHED',
    postedAt: new Date('2024-01-09'),
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-09'),
    applicationsCount: 52,
  },
  {
    id: '8',
    employerId: '3',
    employer: mockCompanies[2],
    title: 'Marketing Specialist',
    locationCity: 'Riyadh',
    locationRegion: 'Riyadh',
    employmentType: 'FULL_TIME',
    salaryMin: 12000,
    salaryMax: 18000,
    currency: 'SAR',
    experienceLevel: 'MID',
    categoryId: 'sales',
    description: 'STC is looking for a creative Marketing Specialist to drive brand awareness and customer engagement.',
    responsibilities: 'Develop marketing campaigns\nManage social media presence\nAnalyze campaign performance\nCoordinate with agencies',
    requirements: '4+ years marketing experience\nDigital marketing expertise\nContent creation skills\nData-driven mindset',
    benefits: 'Flexible work\nCreative environment\nTraining programs\nTeam events',
    status: 'PUBLISHED',
    postedAt: new Date('2024-01-08'),
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    applicationsCount: 73,
  },
  {
    id: '9',
    employerId: '2',
    employer: mockCompanies[1],
    title: 'Urban Planner',
    locationCity: 'NEOM',
    locationRegion: 'Tabuk',
    employmentType: 'FULL_TIME',
    salaryMin: 25000,
    salaryMax: 42000,
    currency: 'SAR',
    experienceLevel: 'SENIOR',
    categoryId: 'construction',
    description: 'Help design the cities of tomorrow at NEOM. We need visionary urban planners.',
    responsibilities: 'Develop master plans\nConduct feasibility studies\nCoordinate with architects\nEnsure sustainable design',
    requirements: 'Masters in Urban Planning\n8+ years experience\nSustainable design expertise\nBIM software proficiency',
    benefits: 'Unique career opportunity\nCompetitive package\nInnovative environment\nGlobal impact',
    status: 'PUBLISHED',
    postedAt: new Date('2024-01-07'),
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-07'),
    applicationsCount: 21,
  },
  {
    id: '10',
    employerId: '6',
    employer: mockCompanies[5],
    title: 'HSE Officer',
    locationCity: 'Jeddah',
    locationRegion: 'Makkah',
    employmentType: 'FULL_TIME',
    salaryMin: 10000,
    salaryMax: 15000,
    currency: 'SAR',
    experienceLevel: 'JUNIOR',
    categoryId: 'construction',
    description: 'Alpha Ultimate is hiring an HSE Officer to ensure workplace safety across our projects.',
    responsibilities: 'Conduct safety inspections\nDevelop safety protocols\nTrain workers on HSE\nInvestigate incidents',
    requirements: 'NEBOSH certified\n2+ years HSE experience\nConstruction industry background\nGood communication',
    benefits: 'Safety training\nCareer growth\nInsurance\nTransportation',
    status: 'PUBLISHED',
    postedAt: new Date('2024-01-06'),
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
    applicationsCount: 41,
  },
]

export const mockSeekers = [
  {
    id: 'seeker-1',
    firstName: 'Ahmed',
    lastName: 'Al-Farsi',
    email: 'ahmed.alfarsi@example.com',
    createdAt: '2024-01-03',
    isActive: true,
  },
  {
    id: 'seeker-2',
    firstName: 'Layla',
    lastName: 'Khalid',
    email: 'layla.khalid@example.com',
    createdAt: '2024-01-05',
    isActive: true,
  },
  {
    id: 'seeker-3',
    firstName: 'Omar',
    lastName: 'Hassan',
    email: 'omar.hassan@example.com',
    createdAt: '2024-01-07',
    isActive: false,
  },
]

export const mockApplications: JobApplication[] = [
  {
    id: 'app-1',
    jobId: '1',
    seekerId: 'seeker-1',
    status: 'SUBMITTED',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'app-2',
    jobId: '2',
    seekerId: 'seeker-2',
    status: 'VIEWED',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: 'app-3',
    jobId: '3',
    seekerId: 'seeker-3',
    status: 'SUBMITTED',
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
]
